### ISSUE TITLE
自定义header头无法提交到dtm

### ISSUE THREAD

**Issue by itkld** [kxg3030/dtmcli-php#3]
Hi 伙计们，代码中出现的 "headers" => $this->branchHeader， 全部通过guzzle提交，其实是post了中带了头信息，dtm无法接收。需要添加到content中，示例：
return $this->submitRequest([
            "gid"         => $this->transGid,
            "trans_type"  => DtmConstant::SagaTrans,
            "steps"       => $this->transSteps,
            "payloads"    => $this->payloads,
            "wait_result" => $this->waitResult,
            "branch_headers" => '{"test_header":"test"}',
        ]);

**Comment by kxg3030** [comment]
你是对的，谢谢你的提醒，我会在下一个提交中修改它
